### ISSUE TITLE
GraphQL API Error when there are no content types

### ISSUE THREAD

**Issue by franzwilding** [unite-cms/standard#22]

**Comment by stefan-kamsker** [comment]
i pushed some to code to bug/22 branch
https://github.com/unite-cms/CoreBundle/commit/c7fa56748466f34caa86f428e5f63dad75443b33

the expected behavior is not clear to me.
what should happen if there are no content types=invalid schema?
the user is currently able to add a domain with empty content types.

thank you :)

**Comment by stefan-kamsker** [comment]
or should SchemaTypeManager implement fe. a method "validateSchema" ? which would be called before the schema build.
but the outcome would be also be an error message fe "no schema available for this domain"

**Comment by franzwilding** [comment]
So the problem is: 

If there are no content or setting types defined, the Mutation schema type object will have no fields. However a graphql object must always have at least one field. 

The query object always have the generic find method, so there is no problem. A simple solution would be to only include the Mutation root-object if there is at least one content or setting type available for the current domain. This could be done directly in GraphQLApiController
